---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.11
  - name: debian-8.6
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[nodejs::default]
      - recipe[yarn::default]
    attributes:
